apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "azure-pipelines-agent.fullname" . }}
  labels:
    {{- include "azure-pipelines-agent.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "azure-pipelines-agent.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "azure-pipelines-agent.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "azure-pipelines-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "azure-pipelines-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.pipelines.agent.mountDocker }}
          securityContext:
            privileged: true
            {{- if .Values.securityContext }}
            {{- with .Values.securityContext }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}
          {{- else }}
            {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- end }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AZP_AGENT_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: AZP_URL
              value: {{ .Values.pipelines.url | quote }}
            - name: AZP_POOL
              value: {{ .Values.pipelines.pool | quote  }}
            - name: AZP_WORK
              value: {{ .Values.pipelines.agent.workDir | quote  }}
            - name: AZP_TOKEN
              {{- if .Values.pipelines.pat.secretRef }}
              {{- with .Values.pipelines.pat.secretRef }}
              valueFrom:
                secretKeyRef:
                  {{- toYaml . | nindent 18 }}
              {{- end }}
              {{- else }}
              value: {{ .Values.pipelines.pat.value | quote }}
              {{- end }}
            {{- with .Values.additionalEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- include "azure-pipelines-agent.volumeMounts" . | nindent 10 -}}
      {{- include "azure-pipelines-agent.volumes" . | nindent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
