# Default values for azure-pipelines-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: emberstack/azure-pipelines-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


# Pat: Can be either a string or a reference to a secret.
# If it is a string, it is used as the value of the secret:
#
# value: "my-secret"
#
# If it is a reference to a secret:
# secretRef:
#   name: my-secret
#   key: my-key
pipelines:
  url: ""
  pat:
    value: ""
    #secretRef: {}
  pool: "Default"
  agent:
    name: ""
    mountDocker: false
    workDir: "_work"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Sets the agent as a cluster admin (useful if you want the agent to manage the cluster)
  clusterAdmin: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Additional environment variables for the agent container.
# Like:
# - name: XXX
#   value: "YYY"
#
# or reference to a secret or configmap:
# - name: SPECIAL_LEVEL_KEY
#   valueFrom:
#     configMapKeyRef:
#       name: special-config
#       key: special.how
#
# - name: SECRET_KEY
#   valueFrom:
#     secretKeyRef:
#       name: secret-name
#       key: secret.key
additionalEnv: []

# Additional volumes for the agent pod.
# extraVolumes:
#   - name: config-volume
#     configMap:
#      name: special-config
extraVolumes: []

# Additional volume mounts for the agent container.
# extraVolumeMounts:
#   - name: config-volume
#     mountPath: /etc/special
#     readOnly: true
extraVolumeMounts: []

# InitContainers for the agent pod.
#
# initContainers:
#   - name: init-container
#     image: busybox
#     command: ["/bin/sh", "-c", "echo Hello World"]
initContainers: []